# https://suzuki-shunsuke.github.io/tfcmt/config
repo_owner: EunyoungPark327
repo_name: terragrunt
terraform:
  plan:
    disable_label: true
    when_no_changes:
      disable_comment: true
    template: |
      {{ .Message }}
      {{if .Result}}
      ```
      {{ .Result }}
      ```
      {{end}}
      ```
      {{ .Body }}
      ```
  apply:
    when_no_changes:
      disable_comment: true
    template: |
      {{ .Message }}
      {{if .Result}}
      ```
      {{ .Result }}
      ```
      {{end}}
      ```
      {{ .Body }}
      ```
